name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Backport
    steps:
      - name: Backport
        uses: VachaShah/backport@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: 'backport/test'
