name: Dependabot PR actions
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Gradle SHAs
        run: |
          ./gradlew updateSHAs

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Updating SHAs
          branch: ${{ github.head_ref }}
          commit_author: ${GITHUB_ACTOR}
          commit_options: '--signoff'
#         run: |
#           echo "Committing the SHA updates"
#           git config user.name "GitHub Actions Bot"
#           git config user.email "<>"
#           git add .
#           git commit -m "Updating SHAs"
#           git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}

      - name: Run spotless
        run: |
          ./gradlew spotlessApply
