name: Dependabot PR actions
on: pull_request
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update Gradle SHAs
        run: |
          ./gradlew updateSHAs

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Updating SHAs
          branch: ${{ github.head_ref }}
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'

      - name: Run spotless
        run: |
          ./gradlew spotlessApply

      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Spotless formatting
          branch: ${{ github.head_ref }}
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
