name: Dependabot PR actions
on: pull_request

jobs:
  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_id: 22958780

      - name: Check out code
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v2
        with:
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Update Gradle SHAs
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          ./gradlew updateSHAs

      - name: Commit the changes
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Updating SHAs
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'

      - name: Run spotless
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          ./gradlew spotlessApply

      - name: Commit the changes
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Spotless formatting
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'
