name: Dependabot PR actions
on: pull_request_target

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      # - name: Obtain GitHub App Installation Access Token
      #   id: githubAppAuth
      #   run: |
      #     TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
      #     echo "::add-mask::$TOKEN"
      #     echo "::set-output name=token::$TOKEN"
      # - name: Use the obtained token
      #   run: |
      #     curl -X POST -H 'Content-Type: application/json' \
      #       -d '{"context":"test","state":"success"}' \
      #       "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA?access_token=$GITHUB_TOKEN"
      #   env:
      #     GITHUB_APP_TOKEN: ${{ steps.githubAppAuth.outputs.token }}

      - name: Check out code
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.GITHUB_APP_TOKEN }}

      - name: Update Gradle SHAs
        run: |
          ./gradlew updateSHAs
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Updating SHAs
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'

      - name: Run spotless
        run: |
          ./gradlew spotlessApply
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: Spotless formatting
          branch: ${{ github.head_ref }}
          commit_user_name: dependabot[bot]
          commit_user_email: support@github.com
          commit_options: '--signoff'